const WIKI = (file) => `https://commons.wikimedia.org/wiki/Special:Redirect/file/${encodeURIComponent(file)}`;

const ASSETS_DATA = {
  FR: { label: "France", flag: "fr", files: ["af.svg", "upr.png", "r!.png", "dlf.svg", "il.png", "rn.png", "udr.svg", "rpf.svg", "ump.png", "lr.png", "horizons.png", "pr.png", "re.png", "modem.png", "pp.png", "ps.png", "sfio.svg", "gens.png", "apres.png", "lfi.png", "pcf.png", "eelv.png", "nfp.png", "nupes.png", "cgt.png"] },
  UK: { label: "Royaume-Uni", flag: "gb", files: ["ukip.png", "adv.jpg", "rest.png", "ref.png", "cons.png", "lab.png", "liberal.png", "libdem.png", "green.png", "yourparty.svg", "snp.png", "sf.png", "dup.png", "cd.png"] },
  TN: { label: "Tunisie", flag: "tn", files: ["true25july.png", "ptr.png", "psd.png", "pup.png", "el-amen.png", "fsn.png", "mup.png", "haq.png", "ptv.png", "hizbelhiraq.png", "mjt.png", "mds.png", "ppt.png", "mta.png", "upr.png", "nidaatounes.png", "wafa.png", "paritsocalliberal.png", "ppds.png", "aljoumhouri.png", "mrt.png", "al-massar.png", "pvp.png", "baath.png", "thirdrepublic.png", "echaab.png", "tnp.png", "ennahdha.png", "upl.png", "errahmah.png", "watad.png", "ettakatol.png", "qalbtounes.png", "frontpopulaire.png", "tahyatounes.png", "25july.png", "albadil.png", "alkarama.png", "azimoun.png", "attayar.png", "cn.png", "alamal.png", "pdl.png", "al-qotb.png", "plt.png", "afektounes.png", "popularcurrent.png", "ps.png", "pt.png", "ptpd.png"] },
  BE: { label: "Belgique", flag: "be", files: [{ name: "N-VA", src: WIKI("N-VA logo.svg") }, { name: "MR", src: WIKI("MR logo 2023.svg") }, { name: "PS", src: WIKI("Socialist Party (Belgium) logo.svg") }, { name: "Vooruit", src: WIKI("Vooruit logo (2020).svg") }, { name: "Vlaams Belang", src: WIKI("Logo Vlaams Belang.svg") }, { name: "Groen", src: WIKI("Groen logo 2022.svg") }, { name: "Les Engagés", src: WIKI("Logo les Engagés 2022.svg") }] },
  CA: { label: "Canada", flag: "ca", files: [{ name: "Parti libéral du Canada", src: WIKI("Liberale Partei Kanadas Logo.svg") }, { name: "Parti conservateur du Canada", src: WIKI("Logo of the Conservative Party of Canada (2023–present).svg") }, { name: "NPD", src: WIKI("NDP-NPD Canada.svg") }, { name: "Bloc Québécois", src: WIKI("Bloc Québécois-logo.svg") }] },
  QC: { label: "Québec", flag: "ca", flagSrc: WIKI("Flag of Quebec.svg"), region: "QC", files: [{ name: "Coalition Avenir Québec", src: WIKI("CAQ logo updated in November 2015.svg") }, { name: "Parti Québécois", src: WIKI("Parti Quebecois.svg") }, { name: "Québec solidaire", src: WIKI("Logo de Québec solidaire.svg") }, { name: "Parti libéral du Québec", src: WIKI("Logo du Parti libéral du Québec (2022 - aujourd'hui).svg") }, { name: "Parti conservateur du Québec", src: WIKI("Logo conservateur bleu.svg") }] },
  US: { label: "États-Unis", flag: "us", files: [{ name: "Democratic Party", src: WIKI("US Democratic Party 2025 logo (positive).svg") }, { name: "Republican Party", src: WIKI("GOP logo (positive).svg") }] },
  DE: { label: "Allemagne", flag: "de", files: [{ name: "CDU/CSU", src: WIKI("CDU Logo 2023.svg") }, { name: "SPD", src: WIKI("SPD-Logo 2022 (text).svg") }, { name: "Alliance 90/Les Verts", src: WIKI("Bündnis 90 - Die Grünen Logo.svg") }] },
  ES: { label: "Espagne", flag: "es", files: [{ name: "PSOE", src: WIKI("Logotipo del PSOE.svg") }, { name: "Partido Popular", src: WIKI("Logo del PP (2022).svg") }, { name: "Vox", src: WIKI("Vox logo.svg") }, { name: "Sumar", src: WIKI("Sumar logo.svg") }] },
  IT: { label: "Italie", flag: "it", files: [{ name: "Fratelli d'Italia", src: WIKI("Fratelli d'Italia logo.svg") }, { name: "Partito Democratico", src: WIKI("Partito Democratico (Italy) logo.svg") }, { name: "Forza Italia", src: WIKI("Forza Italia logo.svg") }, { name: "Lega", src: WIKI("Lega Nord logo.svg") }] },
  PT: { label: "Portugal", flag: "pt", files: [{ name: "PSD", src: WIKI("PSD logo.svg") }, { name: "Partido Socialista", src: WIKI("Partido Socialista (Portugal) logo.svg") }, { name: "Chega", src: WIKI("Chega logo.svg") }, { name: "Iniciativa Liberal", src: WIKI("Iniciativa Liberal logo.svg") }] },
  NL: { label: "Pays-Bas", flag: "nl", files: [{ name: "VVD", src: WIKI("VVD logo.svg") }, { name: "GroenLinks-PvdA", src: WIKI("GroenLinks-PvdA logo.svg") }, { name: "PVV", src: WIKI("PVV logo.svg") }, { name: "D66", src: WIKI("D66 logo.svg") }] },
  CH: { label: "Suisse", flag: "ch", files: [{ name: "UDC/SVP", src: WIKI("SVP Schweiz logo.svg") }, { name: "Parti socialiste", src: WIKI("SP Schweiz logo.svg") }, { name: "PLR/FDP", src: WIKI("FDP.The Liberals logo.svg") }, { name: "Le Centre", src: WIKI("The Centre Switzerland logo.svg") }] },
  AT: { label: "Autriche", flag: "at", files: [{ name: "ÖVP", src: WIKI("Austrian People's Party logo.svg") }, { name: "SPÖ", src: WIKI("SPÖ logo.svg") }, { name: "FPÖ", src: WIKI("Freedom Party of Austria logo.svg") }, { name: "NEOS", src: WIKI("NEOS logo.svg") }] },
  PL: { label: "Pologne", flag: "pl", files: [{ name: "Koalicja Obywatelska", src: WIKI("Civic Coalition logo.svg") }, { name: "PiS", src: WIKI("Law and Justice logo.svg") }, { name: "Lewica", src: WIKI("New Left (Poland) logo.svg") }, { name: "Konfederacja", src: WIKI("Confederation Liberty and Independence logo.svg") }] },
  SE: { label: "Suède", flag: "se", files: [{ name: "Socialdemokraterna", src: WIKI("Swedish Social Democratic Party logo.svg") }, { name: "Moderaterna", src: WIKI("Moderate Party logo.svg") }, { name: "Sverigedemokraterna", src: WIKI("Sweden Democrats logo.svg") }, { name: "Vänsterpartiet", src: WIKI("Left Party (Sweden) logo.svg") }] },
  NO: { label: "Norvège", flag: "no", files: [{ name: "Arbeiderpartiet", src: WIKI("Norwegian Labour Party logo.svg") }, { name: "Høyre", src: WIKI("Conservative Party (Norway) logo.svg") }, { name: "Fremskrittspartiet", src: WIKI("Progress Party Norway logo.svg") }, { name: "SV", src: WIKI("Socialist Left Party (Norway) logo.svg") }] },
  DK: { label: "Danemark", flag: "dk", files: [{ name: "Socialdemokratiet", src: WIKI("Social Democrats (Denmark) logo.svg") }, { name: "Venstre", src: WIKI("Venstre Denmark logo.svg") }, { name: "Dansk Folkeparti", src: WIKI("Danish People's Party logo.svg") }, { name: "Enhedslisten", src: WIKI("Red-Green Alliance (Denmark) logo.svg") }] },
  GR: { label: "Grèce", flag: "gr", files: [{ name: "Nouvelle Démocratie", src: WIKI("New Democracy (Greece) logo.svg") }, { name: "SYRIZA", src: WIKI("SYRIZA logo.svg") }, { name: "PASOK", src: WIKI("PASOK logo.svg") }, { name: "Solution grecque", src: WIKI("Greek Solution logo.svg") }] },
  IE: { label: "Irlande", flag: "ie", files: [{ name: "Fianna Fáil", src: WIKI("Fianna Fáil logo.svg") }, { name: "Fine Gael", src: WIKI("Fine Gael logo.svg") }, { name: "Sinn Féin", src: WIKI("Sinn Féin logo.svg") }, { name: "Labour Party", src: WIKI("Labour Party Ireland logo.svg") }] },
  AU: { label: "Australie", flag: "au", files: [{ name: "Australian Labor Party", src: WIKI("Australian Labor Party logo.svg") }, { name: "Liberal Party of Australia", src: WIKI("Liberal Party of Australia logo.svg") }, { name: "Australian Greens", src: WIKI("Australian Greens logo.svg") }, { name: "One Nation", src: WIKI("Pauline Hanson's One Nation logo.svg") }] },
  JP: { label: "Japon", flag: "jp", files: [{ name: "Parti libéral-démocrate", src: WIKI("Liberal Democratic Party (Japan) logo.svg") }, { name: "Constitutional Democratic Party", src: WIKI("Constitutional Democratic Party of Japan logo.svg") }, { name: "Komeito", src: WIKI("Komeito logo.svg") }, { name: "Parti communiste japonais", src: WIKI("Japanese Communist Party logo.svg") }] }
};
